version: 2

sources:
  - name: sales
    schema: raw
    tables:
      - name: countryregioncurrency
      - name: creditcard
      - name: currency
      - name: currencyrate
      - name: customer
      - name: personcreditcard
      - name: salesorderdetail
      - name: salesorderheader
      - name: salesorderheadersalesreason
      - name: salesperson
      - name: salesreason
      - name: salestaxrate
      - name: salesterritory
      - name: shoppingcartitem
      - name: specialoffer
      - name: specialofferproduct
      - name: store